name: Bug Report
description: When a feature is not behaving as expected.
labels: [bug]
assignees: paradoxical-autumn
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug?
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Add media to help explain your problem
    validations:
      required: false
  - type: dropdown
    id: platforms
    attributes:
      label: What Platforms does this occur on?
      multiple: true
      options:
        - "Windows"
        - "Linux"
        - "Standalone"
    validations:
      required: true
  - type: textarea
    id: log-files
    attributes:
      label: Log Files
      description: Please provide a clean log file from replicating this issue.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
