name: Feature Request
description: Recommend a feature for consideration.
labels: [enhancement]
assignees: paradoxical-autumn, ErrorJan
body:
  - type: dropdown
    id: areas
    attributes:
      label: What areas of the plugin does this apply to?
      multiple: true
      options:
        - "Arbitrary Component Access (ACA)"
        - "Engine Shenanigans (Other Dangerous Features)"
        - "Other/New section"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
